name = "online-collaboration-platform"
compatibility_date = "2025-10-02"
pages_build_output_dir = "./public"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "online-collaboration-platform"

[[r2_buckets]]
binding = "AUDIT_LOGS_BUCKET"
bucket_name = "online-collaboration-platform-logs"

[[kv_namespaces]]
binding = "AUDIT_LOGS_KV"
id = "a4affd1c3cc047b8b9047fc340f82991" # Placeholder - Wrangler will create a real one
preview_id = "a4affd1c3cc047b8b9047fc340f82991" # Placeholder
