name = "online-collaboration-platform"
compatibility_date = "2025-10-02"
pages_build_output_dir = "./public"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "online-collaboration-platform"

[[r2_buckets]]
binding = "BLOCKS_BUCKET"
bucket_name = "online-collaboration-platform-blocks"
